const List= [
    
    {
        name:"Rook",
        id: 1,
        team: "Black",
        startC:1,
        startR:1,
        curC:1,
        curR:1,
    },
    {
        name:"Knight",
        id: 2,
        team: "Black",
        startC:2,
        startR:1,
        curC:2,
        curR:1,
    },
    {
        name:"Bishop",
        id: 3,
        team: "Black",
        startC:3,
        startR:1,
        curC:3,
        curR:1,
    },
    {
        name:"King",
        id: 4,
        team: "Black",
        startC:4,
        startR:1,
        curC:4,
        curR:1,
    },
    {
        name:"Queen",
        id: 5,
        team: "Black",
        startC:5,
        startR:1,
        curC:5,
        curR:1,
    },
    {
        name:"Bishop",
        id: 6,
        team: "Black",
        startC:6,
        startR:1,
        curC:6,
        curR:1,
    },
    {
        name:"Knight",
        id: 7,
        team: "Black",
        startC:7,
        startR:1,
        curC:7,
        curR:1,
    },
    {
        name:"Rook",
        id: 8,
        team: "Black",
        startC:8,
        startR:1,
        curC:8,
        curR:1,
    },

    {
        name:"Pawn",
        id: 9,
        team: "Black",
        startC:1,
        startR:2,
        curC:1,
        curR:2,
    },
    {
        name:"Pawn",
        id: 10,
        team: "Black",
        startC:2,
        startR:2,
        curC:2,
        curR:2,
    },
    {
        name:"Pawn",
        id: 11,
        team: "Black",
        startC:3,
        startR:2,
        curC:3,
        curR:2,
    },
    {
        name:"Pawn",
        id: 12,
        team: "Black",
        startC:4,
        startR:2,
        curC:4,
        curR:2,
    },
    {
        name:"Pawn",
        id: 13,
        team: "Black",
        startC:5,
        startR:2,
        curC:5,
        curR:2,
    },
    {
        name:"Pawn",
        id: 14,
        team: "Black",
        startC:6,
        startR:2,
        curC:6,
        curR:2,  
    },
    {
        name:"Pawn",
        id: 15,
        team: "Black",
        startC:7,
        startR:2,
        curC:7,
        curR:2,
    },
    {
        name:"Pawn",
        id: 16,
        team: "Black",
        startC:8,
        startR:2,
        curC:8,
        curR:2,
    },

    //Team White

    {
        name:"Rook",
        id: 1,
        team: "White",
        startC:1,
        startR:8,
        curC:1,
        curR:8,
    },
    {
        name:"Knight",
        id: 2,
        team: "White",
        startC:2,
        startR:8,
        curC:2,
        curR:8,
    },
    {
        name:"Bishop",
        id: 3,
        team: "White",
        startC:3,
        startR:8,
        curC:3,
        curR:8,
    },
    {
        name:"King",
        id: 4,
        team: "White",
        startC:4,
        startR:8,
        curC:4,
        curR:8,
    },
    {
        name:"Queen",
        id: 5,
        team: "White",
        startC:5,
        startR:8,
        curC:5,
        curR:8,
    },
    {
        name:"Bishop",
        id: 6,
        team: "White",
        startC:6,
        startR:8,
        curC:6,
        curR:8,
    },
    {
        name:"Knight",
        id: 7,
        team: "White",
        startC:7,
        startR:8,
        curC:7,
        curR:8,
    },
    {
        name:"Rook",
        id: 8,
        team: "White",
        startC:8,
        startR:8,
        curC:8,
        curR:8,
    },

    {
        name:"Pawn",
        id: 9,
        team: "White",
        startC:1,
        startR:7,
        curC:1,
        curR:7,
    },
    {
        name:"Pawn",
        id: 10,
        team: "White",
        startC:2,
        startR:7,
        curC:2,
        curR:7,
    },
    {
        name:"Pawn",
        id: 11,
        team: "White",
        startC:3,
        startR:7,
        curC:3,
        curR:7,
    },
    {
        name:"Pawn",
        id: 12,
        team: "White",
        startC:4,
        startR:7,
        curC:4,
        curR:7,
    },
    {
        name:"Pawn",
        id: 13,
        team: "White",
        startC:5,
        startR:7,
        curC:5,
        curR:7,
    },
    {
        name:"Pawn",
        id: 14,
        team: "White",
        startC:6,
        startR:7,
        curC:6,
        curR:7,  
    },
    {
        name:"Pawn",
        id: 15,
        team: "White",
        startC:7,
        startR:7,
        curC:7,
        curR:7,
    },
    {
        name:"Pawn",
        id: 16,
        team: "White",
        startC:8,
        startR:7,
        curC:8,
        curR:7,
    },

    
    
]

export default List